name: Athletic_Plugin
version: '1.0-SNAPSHOT'
main: net.mochinekoserver.athletic_plugin.Main
api-version: '1.20'

commands:
  hide:
    description: プレイヤーを非表示にするコマンド
  show:
    description: プレイヤーを表示するコマンド
  start_mytimer:
    description: 自分のタイマーを開始させるコマンド
  stop_mytimer:
    description: 自分のタイマーを停止させるコマンド
  start_globaltimer:
    description: 全体のタイマーを開始させるコマンド
    permission: net.mochinekoserver.athletic_plugin.start_globaltimer
  stop_globaltimer:
    description: 全体のタイマーを停止させるコマンド
    permission: net.mochinekoserver.athletic_plugin.stop_globaltimer